### PR TITLE
Put 'Diagram-only' setting in settings panel [#103626652]

### PR DESCRIPTION
**Pull request by knowuh**
@sfentress please review when you have a moment.

This is simple commit, it moves the 'diagram-only' setting into the settings panel.

https://www.pivotaltracker.com/story/show/103626652

### CODE REVIEW

**Comment by sfentress** [comment]
@knowuh This looks fine.

Should the setting be serialized? If someone creates a simplified model, do they expect others to open it as such?

Besides that question, this is all good.

**Comment by knowuh** [comment]
@sfentress -- I also was wondering if we would want to serialize the 'diagramOnly' mode or or not.  
At first it seemed like a simple URL parameter. But in thinking about it, it seems to make sense as part of the model data too.

**Comment by ddamelin** [comment]
Yes we should serialize the advanced settings, including diagram only.

**Comment by sfentress** [comment]
Looks good to me. :+1:

**Pull request merged**
