### PR TITLE
Fix codap undo redo

### PR DESCRIPTION
**Pull request by psndcsrv**
Fixes a bug with batched undoable actions and CODAP

### CODE REVIEW

**Comment by sfentress** [comment]
Besides a minor style question, this all looks good to me.

**Comment by psndcsrv** [comment]
I updated the `successes` checking  with the originally proposed change, which I think is what we concluded in our discussion. I put some comments on it, so that hopefully it'll be clearer.

**Comment by sfentress** [comment]
Looks fine to me.

**Comment by knowuh** [comment]
:+1:

**Pull request merged**
